apps/health_control/urls.py
from django.urls import include, path
from apps.health_control.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'health_control'
urlpatterns = [
    path('list/(?P<patient_id>\d+)/', login_required(HealthControlList.as_view()), name='health_control_list'),
    path('create/(?P<patient_id>\d+)/', login_required(HealthControlCreate.as_view()), name='health_control_create'),
    path('update/<pk>/', login_required(HealthControlUpdate.as_view()), name='health_control_update'),
    path('delete/<pk>/', login_required(HealthControlDelete.as_view()), name='health_control_delete'),
    path('show/<pk>/', login_required(HealthControlShow.as_view()), name='health_control_show'),
]

apps/patient/urls.py
from django.urls import include, path
from apps.patient.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'patient'
urlpatterns = [
    path('index', login_required(PatientList.as_view()), name='patient_index'),
    path('create', login_required(PatientCreate.as_view()), name='patient_create'),
    path('update/<pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('delete/<pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),
    path('show/<pk>/', login_required(PatientShow.as_view()), name='patient_show'),
]

apps/report/urls.py
from django.urls import path
from apps.report.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'report'
urlpatterns = [
    path('', login_required(DDReport.as_view()), name='demographic_data_report'),
    path('(?P<patient_id>\d+)/', login_required(PatientReport.as_view()), name='patient_report'),
]

proyecto_hospital/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.patient.views import * 

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include ('apps.users.urls', namespace="users")),
    path('patient/', include ('apps.patient.urls', namespace="patient")),
    path('configuration/', include ('apps.configuration.urls', namespace="configuration")),
    path(r'^', include('django_telegrambot.urls')),
    path('appointments/', include ('apps.appointment.urls', namespace="appointment")),
    path('health_control/', include ('apps.health_control.urls', namespace="health_control")),
    path('report/', include ('apps.report.urls', namespace="report")),
]

apps/patient/models.py
from django.db import models
from django.core.validators import MinValueValidator
from apps.patient.ResourceCollector import ResourceCollector
from django.core.validators import RegexValidator

class DataDemographic(models.Model):
    fridge = models.CharField(max_length=2, choices=(('Si', 'Si'), ('No', 'No')))
    heating = models.CharField(max_length=25, choices=(ResourceCollector.getTypeOfResource("https://api-referencias.proyecto2017.linti.unlp.edu.ar/tipo-calefaccion")))
    electricity = models.CharField(max_length=2, choices=(('Si', 'Si'), ('No', 'No')))
    typeOfHousing = models.CharField(max_length=25, choices=(ResourceCollector.getTypeOfResource("https://api-referencias.proyecto2017.linti.unlp.edu.ar/tipo-vivienda")))
    pet = models.CharField(max_length=2, choices=(('Si', 'Si'), ('No', 'No')))
    typeOfWater = models.CharField(max_length=25, choices=(ResourceCollector.getTypeOfResource("https://api-referencias.proyecto2017.linti.unlp.edu.ar/tipo-agua")))
    
class Patient(models.Model):
    letters = RegexValidator(r'^[a-zA-Z ]+$', 'Solo se permite ingresar letras.')
    lastName = models.CharField(max_length=50, validators=[letters])
    name = models.CharField(max_length=50, validators=[letters])
    birthday = models.DateField()
    documentType = models.CharField(max_length=15, choices=(ResourceCollector.getTypeOfResource("https://api-referencias.proyecto2017.linti.unlp.edu.ar/tipo-documento")))
    documentNumber = models.IntegerField(validators=[MinValueValidator(500000)])
    address = models.CharField(max_length=80)
    phone = models.CharField(max_length=15)
    healthInsurance = models.CharField(max_length=15, choices=(ResourceCollector.getTypeOfResource("https://api-referencias.proyecto2017.linti.unlp.edu.ar/obra-social")))
    gender = models.CharField(max_length=15, choices=(('Masculino', 'Masculino'), ('Femenino', 'Femenino')))
    dataDemographic = models.OneToOneField(DataDemographic, null=True, blank=True, on_delete=models.CASCADE)

apps/patient/forms.py
from django import forms
from apps.patient.models import Patient, DataDemographic

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = (
                    'lastName',
                    'name',
                    'birthday',
                    'documentType',
                    'documentNumber',
                    'address',
                    'phone',
                    'healthInsurance',
                    'gender',
                )
        labels = {
            'lastName': 'Apellido',
            'name': 'Nombre',
            'birthday': 'Fecha de nacimiento (DD/MM/AAAA)',
            'documentType': 'Tipo de documento',
            'documentNumber': 'Número de documento',
            'address': 'Dirección',
            'phone': 'Teléfono',
            'healthInsurance': 'Obra social',
            'gender': 'Género',
        }

        widges = {
            'lastName': forms.CharField(max_length=50, min_length=1),
            'name': forms.CharField(max_length=50, min_length=1),
            'address': forms.CharField(max_length=100, min_length=5),
            'phone': forms.CharField(max_length=30, min_length=6),
        }

        def __init__(self, *args, **kwargs):
            super(PatientForm, self).__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class DataDemographicForm(forms.ModelForm):
    class Meta:
        model = DataDemographic
        fields = (
                'fridge',
                'heating',
                'electricity',
                'typeOfHousing',
                'pet',
                'typeOfWater',
                )
        labels = {
            'fridge': 'Heladera',
            'heating': 'Calefacción',
            'electricity': 'Electricidad',
            'typeOfHousing': 'Tipo de vivienda',
            'pet': 'Mascota',
            'typeOfWater': 'Tipo de agua',
        }

        def __init__(self, *args, **kwargs):
            super(DataDemographicForm, self).__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

apps/patient/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from apps.patient.forms import PatientForm, DataDemographicForm
from apps.patient.models import Patient, DataDemographic
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from maintenance_mode.core import get_maintenance_mode

import requests

class IndexView(TemplateView):
    template_name = 'index/index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if get_maintenance_mode():
                return redirect(reverse_lazy('users:users_login'))                
            else:
                return redirect(reverse_lazy('patient:patient_index'))

        return super(IndexView, self).dispatch(request, *args, **kwargs)

class PatientList(PermissionRequiredMixin, ListView):
    permission_required = 'patient.patient_index'
    permission_denied_message = 'Acceso denegado. No posees permiso para listar pacientes. Contacta a tu administrador'
    raise_exception = True

    model = Patient 
    template_name = 'patient/index.html'

    #MyModel.objects.filter(..).update(my_attr=True)

class PatientCreate(PermissionRequiredMixin, CreateView):
    permission_required = ("patient.patient_update", "patient.dataDemographic_update")
    permission_denied_message = 'Acceso denegado. No posees permiso para crear una paciente. Contacta a tu administrador'
    raise_exception = True

    model = Patient
    form_class = PatientForm
    second_form_class = DataDemographicForm
    template_name = 'patient/create.html'
    success_url = reverse_lazy('patient:patient_index')
    
    def get_context_data(self, **kwargs):
        context = super(PatientCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context: #form2 es el formulario de los datos demográficos
            context['form2'] = self.second_form_class() # Los mensajes de error se van si saco ese self.request.GET
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST) #Tomo valores de formulario 1 (patient)
        form2 = self.second_form_class(request.POST) #Tomo valores de formulario 2 (dataDemographic)
        if form.is_valid() and form2.is_valid(): 
            patient = form.save(commit=False) 
            patient.dataDemographic = form2.save() #Creamos las relaciones
            patient.save() #Guardamos todo
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2= form2)) #Devolvemos formularios en blanco

class PatientUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ("patient.patient_update", "patient.dataDemographic_update")
    permission_denied_message = 'Acceso denegado. No posees permiso para actualizar un paciente. Contacta a tu administrador'
    raise_exception = True

    model = Patient
    second_model = DataDemographic
    form_class = PatientForm
    second_form_class = DataDemographicForm
    template_name = 'patient/update.html'
    success_url = reverse_lazy('patient:patient_index')

    def get_context_data(self, **kwargs):
        context = super(PatientUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        patient = self.model.objects.get(id=pk)
        dataDemographic = self.second_model.objects.get(id=patient.dataDemographic_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=dataDemographic)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_patient = kwargs['pk']
        patient = self.model.objects.get(id=id_patient)
        dataDemographic = self.second_model.objects.get(id=patient.dataDemographic_id)
        form = self.form_class(request.POST, instance=patient)
        form2 = self.second_form_class(request.POST, instance=dataDemographic)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())
            

class PatientDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ("patient.patient_destroy", "patient.dataDemographic_destroy")
    permission_denied_message = 'Acceso denegado. No posees permiso para borrar un paciente. Contacta a tu administrador'
    raise_exception = True

    model = Patient
    template_name = 'patient/delete.html'
    success_url = reverse_lazy('patient:patient_index')

class PatientShow(PermissionRequiredMixin, DetailView):
    permission_required = ("patient.patient_show", "patient.dataDemographic_show")
    permission_denied_message = 'Acceso denegado. No posees permiso para ver un paciente. Contacta a tu administrador'
    raise_exception = True

    model = Patient
    template_name = 'patient/show.html'

templates/patient/create.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

    <div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Nuevo paciente 
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <legend>Datos personales </legend>
                            {% for field in form %}
                                <div class="form-group col-md-6">
                                    {% bootstrap_field field %}
                                </div>
                            {% endfor %}
                            <legend>Datos demográficos</legend>
                            {% for field in form2 %}
                                <div class="form-group col-md-6">
                                    {% bootstrap_field field %}
                                </div>
                            {% endfor %}
                        </div>
                        {% bootstrap_button "Guardar" button_type="submit" button_class="btn btn-primary" %}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/patient/delete.html
{% load bootstrap4 %}
{% block content %}

<form role="form" action="{% url 'patient:patient_delete' object.pk %}" method="post">
    {% csrf_token %}
    <p>Desea eliminar al paciente {{object.lastName}}, {{ object.name }} ?</p>
    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-default" onclick="return cerrar_modal()">Cancelar</a>
</form>

{% endblock %}

{% block finish %}
<script>
    function cerrar_modal(){
        modal.dialog("close");
    }
</script>
{% endblock %}

templates/patient/index.html
{% extends 'base/list.html' %}
{% load bootstrap4 %}
{% load configuration_tags %}
{% load staticfiles %}

{% block card-top %}
    <div class="card-header">
        Registro de pacientes
    </div>
    <img class="card-img-top" src="{% static 'img/patients.jpg' %}" alt="Card image cap">
{% endblock %}  

    {% block fieldsHeadPrincipalTable %}
        <th>Apellido</th>
        <th>Nombre</th>
        <th>Número de documento</th>
        <th>Historia Clinica</th>
        <th>Perfil</th>
    {% endblock %}

      
    {% block fieldsBodyPrincipalTable %}
        {% for patient in object_list %}
            <tr>
            <td>{{ patient.lastName }}</td>
            <td>{{ patient.name }}</td>
            <td>{{ patient.documentNumber }}</td>
            {% url 'health_control:health_control_list' patient.id as list_url %}
            <td>{% bootstrap_button "Detalles" button_type="link" button_class="btn btn-primary btn-sm" href=list_url %}</td>
            <td><a href="{% url 'patient:patient_show' patient.id %}" class="btn btn-primary btn-sm">Perfil</a></td>
            </tr>
        {% endfor %}
    {% endblock %}

    {% block card-footer %}
        <div class="card-footer bg-transparent">
            <a href="{% url 'report:demographic_data_report' %}" class="btn btn-primary btn-sm">Reporte de datos demográficos</a>
        </div>
    {% endblock %} 

{% block finish %}
    <script>
        $(document).ready(function() 
        {   
            var table = $('#mytable').DataTable( {
                "responsive": true,
                "language": {
                    url: "/static/localizacion/es_ES.json"
                },
                "aoColumnDefs": [{ 
                "bSortable": false,
                "aTargets": [3,4]
                }],
                "lengthChange": false,
                "pageLength": {% items_per_page %}
            } );
        });
    </script>    
{% endblock %}

templates/patient/show.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Detalles de {{ object.lastName }}, {{ object.name }}
                </div>
                <div class="card-body">
                    <table class="table table-hover text-center">
                        <tbody>
                            <tr>
                                <td>Apellido:</td>
                                <td>{{ object.lastName }}</td>
                            </tr>
                            <tr>
                                <td>Nombre:</td>
                                <td>{{ object.name }}</td>
                            </tr>
                            <tr>
                                <td>Fecha de nacimiento:</td>
                                <td>{{ object.birthday }}</td>
                            </tr>
                            <tr>
                                <td>Género:</td>
                                <td>{{ object.gender }}</td>
                            </tr>
                            <tr>
                                <td>Tipo de documento:</td>
                                <td>{{ object.documentType }}</td>
                            </tr>
                            <tr>
                                <td>Número de documento:</td>
                                <td>{{ object.documentNumber }}</td>
                            </tr>
                            <tr>
                                <td>Domicilio:</td>
                                <td>{{ object.address }}</td>
                            </tr>
                            <tr>
                                <td>Teléfono / Celular:</td>
                                <td>{{ object.phone }}</td>
                            </tr>
                            <tr>
                                <td>Heladera:</td>
                                <td>{{ object.dataDemographic.fridge }}</td>
                            </tr>
                            <tr>
                                <td>Calefacción:</td>
                                <td>{{ object.dataDemographic.heating }}</td>
                            </tr>
                            <tr>
                                <td>Electricidad:</td>
                                <td>{{ object.dataDemographic.electricity }}</td>
                            </tr>
                            <tr>
                                <td>Tipo de vivienda:</td>
                                <td>{{ object.dataDemographic.typeOfHousing }}</td>
                            </tr>
                            <tr>
                                <td>Mascota:</td>
                                <td>{{ object.dataDemographic.pet }}</td>
                            </tr>
                            <tr>
                                <td>Tipo de agua:</td>
                                <td>{{ object.dataDemographic.typeOfWater }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-transparent">
                    <a href="{% url 'patient:patient_update' patient.id %}" class="btn btn-secondary btn-sm">Editar</a></td>                        
                    <!-- hay que ver el rol, para saber si es admin -->
                    <a onclick="return abrir_modal('{% url 'patient:patient_delete' patient.id %}','Eliminar paciente')" class="btn btn-danger btn-sm">
                            Eliminar
                    </a>
                    <a href="{% url 'patient:patient_index' %}" class="btn btn-secondary btn-sm">Volver al listado</a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- MODAL ELIMINAR -->

    <form method="post" class="modal fade" id="modalRemove">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminar paciente</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger">
                        ¿Está seguro de eliminar al paciente {{ object.lastName }}, {{ object.name }}?
                    </div>
                </div>
                <div class="modal-footer ">
                    <input type="hidden" id="deleteId" name="deleteId">
                    <button type="submit" class="btn btn-danger" ><span class="glyphicon glyphicon-ok-sign"></span>Si</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>No</button>
                </div>
            </div>
        </div>
    </form>
    
    <!-- FIN MODAL ELIMINAR -->

{% endblock %}

{% block finish %}
<div id="popup"></div>

<script>
    var modal;
    function abrir_modal(url, titulo){
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 500,
            resizable: false
        }).dialog('open').load(url)
    }

</script>
{% endblock %}

templates/patient/update.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Editar paciente
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <legend>Datos personales </legend>
                            {% for field in form %}
                                <div class="form-group col-md-6">
                                    {% bootstrap_field field %}
                                </div>
                            {% endfor %}
                            <legend>Datos demográficos</legend>
                            {% for field in form2 %}
                                <div class="form-group col-md-6">
                                    {% bootstrap_field field %}
                                </div>
                            {% endfor %}
                        </div>
                        {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary" %}
                    </form>
                </div>
                <div class="card-footer bg-transparent">
                    <a href="{% url 'patient:patient_show' patient.id %}" class="btn btn-secondary btn-sm">Volver al perfil</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}