apps/configuration/urls.py
from django.urls import include, path
from apps.configuration.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'configuration'
urlpatterns = [
    path('', login_required(ConfigurationUpdate.as_view()), name='configuration'),

]

apps/patient/urls.py
from django.urls import include, path
from apps.patient.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'patient'
urlpatterns = [
    path('index', login_required(PatientList.as_view()), name='patient_index'),
    path('create', login_required(PatientCreate.as_view()), name='patient_create'),
    path('update/<pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('delete/<pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),
    path('show/<pk>/', login_required(PatientShow.as_view()), name='patient_show'),
]

apps/users/urls.py
from django.urls import include, path
from apps.users.views import * 
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
    path('register/', login_required(RegisterUser.as_view()), name='users_register'),
    path('login/', login, {'template_name':'users/login.html'}, name='users_login'),
    path('logedin/', login_required(logued_user), name='users_logedin'),
    path('logout/', login_required(logout_then_login), name='users_logout'),
    path('reset/password_reset/', password_reset, {'template_name':'users/password_reset_form.html',
        'email_template_name':'users/password_reset_email.html',
        'post_reset_redirect':'users:users_password_reset_done',}, name='users_password_reset'),
    path('reset/password_reset_done/', password_reset_done, {'template_name':'users/password_reset_done.html',},
        name='users_password_reset_done'),
    path("reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
        password_reset_confirm, {'template_name':'users/password_reset_confirm.html',
        'post_reset_redirect':'users:users_password_reset_complete',},
        name='users_password_reset_confirm'),
    path('reset/password_reset_complete/', password_reset_complete, {'template_name':'users/password_reset_complete.html',},
        name='users_password_reset_complete'),
    path('list/', login_required(UsersList.as_view()), name='users_list'),
    path('update/<pk>/', login_required(UsersUpdate.as_view()), name='users_update'),
    path('delete/<pk>/', login_required(UsersDelete.as_view()), name='users_delete'),
    path('show/<pk>/', login_required(UsersShow.as_view()), name='users_show'),
]

proyecto_hospital/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.patient.views import * 

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include ('apps.users.urls', namespace="users")),
    path('patient/', include ('apps.patient.urls', namespace="patient")),
    path('configuration/', include ('apps.configuration.urls', namespace="configuration")),
    path(r'^', include('django_telegrambot.urls')),
    path('appointments/', include ('apps.appointment.urls', namespace="appointment")),
    path('health_control/', include ('apps.health_control.urls', namespace="health_control")),
    path('report/', include ('apps.report.urls', namespace="report")),
]

templates/base/base.html
{% load staticfiles %}
{% load bootstrap4 %}

{% load configuration_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Franco Liptak - Gastón Ríos">
  <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
  <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
  <link href="{% static 'datatables/datatables.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/demo.css' %}" rel="stylesheet">
  {% block stylesheet %}    
  {% endblock %}
  <title>Hospital Gutiérrez</title>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/">{% title %}</a>
    {% block sideMenu %}    
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Lista de pacientes">
          <a class="nav-link" href="{% url 'patient:patient_index' %}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Lista de pacientes</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Agregar paciente">
          <a class="nav-link" href="{% url 'patient:patient_create' %}">
            <i class="fa fa-fw fa-plus"></i>
            <span class="nav-link-text">Agregar paciente</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Lista de usuarios">
          <a class="nav-link" href="{% url 'users:users_list' %}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Lista de usuarios</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Agregar usuario">
          <a class="nav-link" href="{% url 'users:users_register' %}">
            <i class="fa fa-fw fa-user"></i>
            <span class="nav-link-text">Agregar usuario</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Configuración">
          <a class="nav-link" href="{% url 'configuration:configuration' %}">
            <i class="fa fa-fw fa-area-chart"></i>
            <span class="nav-link-text">Configuración</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Configuración">
          <a class="nav-link" href="{% url 'users:users_show' user.id %}">
            <i class="fa fa-fw fa-user"></i>
            <span class="nav-link-text">Ver mi perfil</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
    </div>
    {% endblock %}

    {% block topMenu %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <span class="nav-link active">{{ user.get_username }}</span>
          </li>
          <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-fw fa-sign-out"></i>Cerrar sesión</a>
          {% else %}
            <a class="nav-link" href="{% url 'users:users_login' %}"
              <i class="fa fa-fw fa-sign-out"></i>Cerrar sesión</a>
          {% endif %}
        </li>
      </ul>
    {% endblock %}
  </nav>
  <div class="content-wrapper">
    <div class="container-fluid">
      

      {% block content %}
      {% endblock %}


    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Proyecto de Software 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">¿Está seguro de cerrar sesión?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Seleccione "Cerrar sesión" si está listo para dejar su sesión actual.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
            <a class="btn btn-danger" href="{% url 'users:users_logout' %}">Cerrar sesión</a>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'datatables/datatables.min.js' %}"></script>
  </div>
  {% block finish %}
  {% endblock %}
</body>

</html>

templates/base/list.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container col-lg-10">
        <div class="card mb-3">
            {% block card-top %}
            {% endblock %}  
            <div class="card-body">
                <div class="container col-md-12">
                    <div class="table-responsive">
                        <table id="mytable" class="table table-bordred table-striped text-center">
                            <thead>
                                <tr>
                                {% block fieldsHeadPrincipalTable %}
                                {% endblock %}  
                                </tr>
                            </thead>
                            <tbody>
                                {% block fieldsBodyPrincipalTable %}
                                {% endblock %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% block card-footer %}
            {% endblock %} 
            <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </button>
                        <h4 class="modal-title custom_align" id="Heading">Editar</h4>
                        </div>
                    </div>
                    <!-- /.modal-content --> 
                </div>
            <!-- /.modal-dialog --> 
            </div>
        </div>
    </div>
{% endblock %}