apps/health_control/urls.py
from django.urls import include, path
from apps.health_control.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'health_control'
urlpatterns = [
    path('list/(?P<patient_id>\d+)/', login_required(HealthControlList.as_view()), name='health_control_list'),
    path('create/(?P<patient_id>\d+)/', login_required(HealthControlCreate.as_view()), name='health_control_create'),
    path('update/<pk>/', login_required(HealthControlUpdate.as_view()), name='health_control_update'),
    path('delete/<pk>/', login_required(HealthControlDelete.as_view()), name='health_control_delete'),
    path('show/<pk>/', login_required(HealthControlShow.as_view()), name='health_control_show'),
]

apps/patient/urls.py
from django.urls import include, path
from apps.patient.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'patient'
urlpatterns = [
    path('index', login_required(PatientList.as_view()), name='patient_index'),
    path('create', login_required(PatientCreate.as_view()), name='patient_create'),
    path('update/<pk>/', login_required(PatientUpdate.as_view()), name='patient_update'),
    path('delete/<pk>/', login_required(PatientDelete.as_view()), name='patient_delete'),
    path('show/<pk>/', login_required(PatientShow.as_view()), name='patient_show'),
]

apps/report/urls.py
from django.urls import path
from apps.report.views import * 
from django.contrib.auth.decorators import login_required

app_name = 'report'
urlpatterns = [
    path('', login_required(DDReport.as_view()), name='demographic_data_report'),
    path('(?P<patient_id>\d+)/', login_required(PatientReport.as_view()), name='patient_report'),
]

proyecto_hospital/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.patient.views import * 

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include ('apps.users.urls', namespace="users")),
    path('patient/', include ('apps.patient.urls', namespace="patient")),
    path('configuration/', include ('apps.configuration.urls', namespace="configuration")),
    path(r'^', include('django_telegrambot.urls')),
    path('appointments/', include ('apps.appointment.urls', namespace="appointment")),
    path('health_control/', include ('apps.health_control.urls', namespace="health_control")),
    path('report/', include ('apps.report.urls', namespace="report")),
]

apps/health_control/models.py
from django.db import models
from django.conf import settings
from apps.patient.models import Patient
from datetime import date

# Create your models here.

class HealthControl(models.Model):
    date = models.DateField(default=date.today)
    age = models.IntegerField()
    weight = models.FloatField()
    vaccines = models.BooleanField()
    vaccines_obs = models.TextField()
    maturation = models.BooleanField()
    maturation_obs = models.TextField()
    phisical_exam = models.BooleanField()
    phisical_exam_obs = models.TextField()
    pc = models.FloatField()
    ppc = models.FloatField()
    height = models.FloatField()
    feeding = models.TextField()
    observations = models.TextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        limit_choices_to={'groups__name': 'pediatra'},
    )
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
    )

apps/health_control/forms.py
from django import forms
from apps.health_control.models import HealthControl

class CreateHealthControlForm(forms.ModelForm):
    class Meta:
        
        model = HealthControl
        fields = (
            'weight',
            'height',
            'vaccines',
            'vaccines_obs',
            'maturation',
            'maturation_obs',
            'phisical_exam',
            'phisical_exam_obs',
            'pc',
            'ppc',
            'feeding',
            'observations',
        )
        labels = {
            'weight': 'Peso',
            'height': 'Talla',
            'vaccines': '¿Vacunas completas?',
            'vaccines_obs': 'Vacunas observaciones',
            'maturation': '¿Maduración acorde?',
            'maturation_obs': 'Maduración observaciones',
            'phisical_exam': '¿Exámen físico normal?',
            'phisical_exam_obs': 'Exámen físico observaciones',
            'pc': 'PC',
            'ppc': 'PPC',
            'feeding': 'Alimentación',
            'observations': 'Observaciones generales',
        }

class UpdateHealthControlForm(forms.ModelForm):
    class Meta:
        
        model = HealthControl
        fields = (
            'date',
            'weight',
            'height',
            'vaccines',
            'vaccines_obs',
            'maturation',
            'maturation_obs',
            'phisical_exam',
            'phisical_exam_obs',
            'pc',
            'ppc',
            'feeding',
            'observations',
            'user',
        )
        labels = {
            'date': 'Fecha',
            'weight': 'Peso',
            'height': 'Talla',
            'vaccines': '¿Vacunas completas?',
            'vaccines_obs': 'Vacunas observaciones',
            'maturation': '¿Maduración acorde?',
            'maturation_obs': 'Maduración observaciones',
            'phisical_exam': '¿Exámen físico normal?',
            'phisical_exam_obs': 'Exámen físico observaciones',
            'pc': 'PC',
            'ppc': 'PPC',
            'feeding': 'Alimentación',
            'observations': 'Observaciones generales',
            'user': 'Pediatra',
        }

apps/health_control/views.py
from django.http import HttpResponseRedirect
from apps.health_control.forms import CreateHealthControlForm, UpdateHealthControlForm
from apps.health_control.models import HealthControl
from apps.patient.models import Patient
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

class HealthControlList(PermissionRequiredMixin, ListView):
    permission_required = 'health_control.health_control_list'
    permission_denied_message = 'Acceso denegado. No posees permiso para listar la historia clinica. Contacta a tu administrador'
    raise_exception = True
    model = HealthControl 
    template_name = 'health_control/list.html'

    def get_queryset(self):
        return HealthControl.objects.filter(patient=self.kwargs['patient_id'])

    def get_context_data(self, **kwargs):
        context = super(HealthControlList, self).get_context_data(**kwargs)
        context['patient_id'] = self.kwargs['patient_id']
        return context

class HealthControlCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'health_control.health_control_update'
    permission_denied_message = 'Acceso denegado. No posees permiso para crear el control de salud. Contacta a tu administrador'
    raise_exception = True
    model = HealthControl
    form_class = CreateHealthControlForm
    template_name = 'health_control/form.html'

    def get_context_data(self, **kwargs):
        context = super(HealthControlCreate, self).get_context_data(**kwargs)
        context['header'] = 'Crear nuevo control medico'
        return context

    def get_success_url(self):
        return reverse_lazy('health_control:health_control_list', kwargs={'patient_id': self.object.patient.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST) #Tomo valores de formulario 1
        if form.is_valid(): 
            health_control = form.save(commit=False) 
            health_control.patient = Patient.objects.get(pk=self.kwargs['patient_id'])
            health_control.user = request.user
            health_control.age = health_control.date - health_control.patient.birthday
            health_control.save() #Guardamos todo
            self.object = health_control
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form)) #Devolvemos formularios en blanco
    
class HealthControlUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'health_control.health_control_update'
    permission_denied_message = 'Acceso denegado. No posees permiso para actualizar el control de salud. Contacta a tu administrador'
    raise_exception = True
    model = HealthControl
    form_class = UpdateHealthControlForm
    template_name = 'health_control/form.html'

    def get_success_url(self):
        return reverse_lazy('health_control:health_control_list', kwargs={'patient_id': self.object.patient.id})

    def get_context_data(self, **kwargs):
        context = super(HealthControlUpdate, self).get_context_data(**kwargs)
        context['header'] = 'Actualizar control medico'
        return context            

    def form_valid(self, form):
        self.object.age = (form.cleaned_data['date'] - self.object.patient.birthday).days
        return super(HealthControlUpdate, self).form_valid(form)

class HealthControlDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'health_control.health_control_destroy'
    permission_denied_message = 'Acceso denegado. No posees permiso para borrar el control de salud. Contacta a tu administrador'
    raise_exception = True
    model = HealthControl
    template_name = 'health_control/delete.html'

    def get_success_url(self):
        return reverse_lazy('health_control:health_control_list', kwargs={'patient_id': self.object.patient.id})

class HealthControlShow(PermissionRequiredMixin, DetailView):
    permission_required = 'health_control.health_control_show'
    permission_denied_message = 'Acceso denegado. No posees permiso para ver el control de salud. Contacta a tu administrador'
    raise_exception = True
    model = HealthControl
    template_name = 'health_control/show.html'

templates/health_control/delete.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            <div class="card-header">
                ¿Desea eliminar el control medico con fecha {{ object.date }}?
            </div>
            <div class="card-body">
                <form  role="form" method="post">
                    {% csrf_token %}
                    {% bootstrap_button "Eliminar" button_type="submit" button_class="btn-primary" %}
                    {% url 'health_control:health_control_list' as list_url %}
                    {% bootstrap_button "Cancelar" button_type="link" button_class="btn-danger" href=list_url %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/health_control/form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    {{ header }} 
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="post">
                        {% csrf_token %}
                        {% if form.user %}
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.date %}
                            </div>
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.weight %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.height %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.vaccines %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.vaccines_obs %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.maturation %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.maturation_obs %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.phisical_exam %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.phisical_exam_obs %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.pc %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.ppc %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.feeding %}
                            </div>
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.observations %}
                            </div>
                        </div>
                        {% if form.user %}
                        <div class="row">
                            <div class="form-group col-md-6">
                                {% bootstrap_field form.user %}
                            </div>
                        </div>
                        {% endif %}
                        {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary" %}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/health_control/list.html
{% extends 'base/list.html' %}
{% load bootstrap4 %}
{% load report_filters %}
{% load configuration_tags %}
{% load staticfiles %}

{% block card-top %}
    <div class="card-header">
        Historia clínica
    </div>
    <img class="card-img-top" src="{% static 'img/historia_clinica.jpg' %}" alt="Card image cap">
{% endblock %}  

    {% block fieldsHeadPrincipalTable %}
        <th>Fecha</th>
        <th>Edad</th>
        <th>Peso</th>
        <th>¿Vacunas completas?</th>
        <th>¿Maduracion acorde?</th>
        <th>¿Examen fisico normal?</th>
        <th>PC</th>
        <th>PPC</th>
        <th>Talla</th>
        <th>Ver Detalles</th>
        <th>Editar</th>
        <th>Eliminar</th>
    {% endblock %}

    {% block fieldsBodyPrincipalTable %}
        {% for health_control in object_list %}
            <tr>
            <td>{{ health_control.date }}</td>
            <td>{{ health_control.age|ages|floatformat:"0" }}</td>
            <td>{{ health_control.weight }}</td>
            <td>{% if health_control.vaccines %} Si {% else %} No {% endif %}</td>
            <td>{% if health_control.maturation %} Si {% else %} No {% endif %}</td>
            <td>{% if health_control.pshisical_exam %} Si {% else %} No {% endif %}</td>
            <td>{{ health_control.pc }}</td>
            <td>{{ health_control.ppc }}</td>
            <td>{{ health_control.height }}</td>
            {% url 'health_control:health_control_show' health_control.id as show_url %}
            <td>{% bootstrap_button "Detalles" button_type="link" button_class="btn btn-primary btn-xs" href=show_url %}</td>
            {% url 'health_control:health_control_update' health_control.id as update_url %}
            <td>{% bootstrap_button "Editar" button_type="link" button_class="btn btn-primary btn-xs" href=update_url %}</td>
            {% url 'health_control:health_control_delete' health_control.id as delete_url %}
            <td>{% bootstrap_button "Eliminar" button_type="link" button_class="btn btn-danger btn-xs" href=delete_url %}</td>
            </tr>
        {% endfor %}
    {% endblock %}

    {% block card-footer %}
        <div class="card-footer bg-transparent">
            {% url 'health_control:health_control_create' patient_id as create_url %}
            {% bootstrap_button "Nuevo Control" button_type="link" button_class="btn btn-primary btn-sm" href=create_url %}
            {% url 'report:patient_report' patient_id as report_url %}
            {% bootstrap_button "Reporte de paciente" button_type="link" button_class="btn btn-primary btn-sm" href=report_url %}

            <a href="{% url 'patient:patient_index' %}" class="btn btn-secondary btn-sm">Volver al listado</a>
        </div>
    {% endblock %} 

{% block finish %}
    <script>
        $(document).ready(function() 
        {   
            var table = $('#mytable').DataTable( {
                "responsive": true,
                "language": {
                    url: "/static/localizacion/es_ES.json"
                },
                "aoColumnDefs": [{ 
                "bSortable": false,
                "aTargets": [9,10,11]
                }],
                "lengthChange": false,
                "pageLength": {% items_per_page %}
            } );
        });
    </script>    
{% endblock %}

templates/health_control/show.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Control medico de {{ object.patient.lastName }} {{ object.patient.name }}  
                </div>
                <div class="card-body">
                    <table class="table table-hover text-center">
                        <tbody>
                            <tr>
                                <td>Fecha:</td>
                                <td>{{ object.date }}</td>
                            </tr>
                            <tr>
                                <td>Edad:</td>
                                <td>{{ object.age }}</td>
                            </tr>
                            <tr>
                                <td>Peso:</td>
                                <td>{{ object.weight }}</td>
                            </tr>
                            <tr>
                                <td>Talla:</td>
                                <td>{{ object.height }}</td>
                            </tr>
                            <tr>
                                <td>¿Vacunas completas?:</td>
                                <td>{% if object.vaccines %} Si {% else %} No {% endif %}</td>
                            </tr>
                            <tr>
                                <td>Vacunas observaciones:</td>
                                <td>{{ object.vaccines_obs }}</td>
                            </tr>
                            <tr>
                                <td>¿Maduracion acorde?:</td>
                                <td>{% if object.maturation %} Si {% else %} No {% endif %}</td>
                            </tr>
                            <tr>
                                <td>Maduracion observaciones:</td>
                                <td>{{ object.maturation_obs }}</td>
                            </tr>
                            <tr>
                                <td>¿Examen fisico normal?:</td>
                                <td>{% if object.phisical_exam %} Si {% else %} No {% endif %}</td>
                            </tr>
                            <tr>
                                <td>Examen fisico observaciones:</td>
                                <td>{{ object.phisical_exam_obs }}</td>
                            </tr>
                            <tr>
                                <td>PC:</td>
                                <td>{{ object.pc }}</td>
                            </tr>
                            <tr>
                                <td>PPC:</td>
                                <td>{{ object.ppc }}</td>
                            </tr>
                            <tr>
                                <td>Alimentacion:</td>
                                <td>{{ object.feeding }}</td>
                            </tr>
                            <tr>
                                <td>Observaciones generales:</td>
                                <td>{{ object.observations }}</td>
                            </tr>
                            <tr>
                                <td>Pediatra:</td>
                                <td>{{ object.user.username }}</td>
                            </tr>
                            <tr>
                                <td>Detalles del paciente:</td>
                                {% url 'patient:patient_show' object.patient.id as patient_url %}
                                <td>{% bootstrap_button "Ir a detalles" button_type="link" button_class="btn btn-primary btn-xs" href=patient_url %}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-transparent">
                    {% url 'health_control:health_control_update' object.id as update_url %}
                    {% bootstrap_button "Editar" button_type="link" button_class="btn btn-primary btn-xs" href=update_url %}
                    {% url 'health_control:health_control_delete' object.id as delete_url %}
                    {% bootstrap_button "Eliminar" button_type="link" button_class="btn btn-danger btn-xs" href=delete_url %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}