apps/users/urls.py
from django.urls import include, path
from apps.users.views import * 
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
    path('register/', login_required(RegisterUser.as_view()), name='users_register'),
    path('login/', login, {'template_name':'users/login.html'}, name='users_login'),
    path('logedin/', login_required(logued_user), name='users_logedin'),
    path('logout/', login_required(logout_then_login), name='users_logout'),
    path('reset/password_reset/', password_reset, {'template_name':'users/password_reset_form.html',
        'email_template_name':'users/password_reset_email.html',
        'post_reset_redirect':'users:users_password_reset_done',}, name='users_password_reset'),
    path('reset/password_reset_done/', password_reset_done, {'template_name':'users/password_reset_done.html',},
        name='users_password_reset_done'),
    path("reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
        password_reset_confirm, {'template_name':'users/password_reset_confirm.html',
        'post_reset_redirect':'users:users_password_reset_complete',},
        name='users_password_reset_confirm'),
    path('reset/password_reset_complete/', password_reset_complete, {'template_name':'users/password_reset_complete.html',},
        name='users_password_reset_complete'),
    path('list/', login_required(UsersList.as_view()), name='users_list'),
    path('update/<pk>/', login_required(UsersUpdate.as_view()), name='users_update'),
    path('delete/<pk>/', login_required(UsersDelete.as_view()), name='users_delete'),
    path('show/<pk>/', login_required(UsersShow.as_view()), name='users_show'),
]

proyecto_hospital/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.patient.views import * 

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include ('apps.users.urls', namespace="users")),
    path('patient/', include ('apps.patient.urls', namespace="patient")),
    path('configuration/', include ('apps.configuration.urls', namespace="configuration")),
    path(r'^', include('django_telegrambot.urls')),
    path('appointments/', include ('apps.appointment.urls', namespace="appointment")),
    path('health_control/', include ('apps.health_control.urls', namespace="health_control")),
    path('report/', include ('apps.report.urls', namespace="report")),
]

apps/users/models.py
from django.db import models

# Create your models here.

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm

class RegisterUserForm(UserCreationForm):

    group = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'group',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Email',            
            'group': 'Tipo de usuario',            
        }

class UpdateUserForm(UserCreationForm):

    group = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'group',
            'is_active',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Email',            
            'group': 'Tipo de usuario',
            'is_active': 'Usuario Activo (no bloqueado)',
        }

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from apps.users.forms import RegisterUserForm, UpdateUserForm
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import PermissionRequiredMixin
from maintenance_mode.core import get_maintenance_mode

class RegisterUser(PermissionRequiredMixin, CreateView):

    permission_required = 'auth.user_update'
    permission_denied_message = 'Acceso denegado. No posees permiso para registrar usuarios. Contacta a tu administrador'
    raise_exception = True

    model = User
    template_name = "users/register.html"
    form_class = RegisterUserForm
    success_url = reverse_lazy("users:users_list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST) #Tomo valores de formulario
        if form.is_valid(): 
            patient = form.save(commit=False)
            patient.save() #Guardamos todo
            patient.groups.add(*form.cleaned_data['group'])
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form)) #Devolvemos formularios en blanco

class UsersList(PermissionRequiredMixin, ListView):
    permission_required = 'auth.user_index'
    permission_denied_message = 'Acceso denegado. No posees permiso para listar usuarios. Contacta a tu administrador'
    raise_exception = True
    
    model = User
    template_name = 'users/list.html'

class UsersShow(PermissionRequiredMixin, DetailView):
    permission_required = 'auth.user_index'
    permission_denied_message = 'Acceso denegado. No posees permiso para ver el perfil de los usuarios. Contacta a tu administrador'
    raise_exception = True

    model = User
    template_name = 'users/show.html'

class UsersDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.user_destroy'
    permission_denied_message = 'Acceso denegado. No posees permiso para borrar usuarios. Contacta a tu administrador'
    raise_exception = True
    model = User
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:users_list')

class UsersUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'auth.user_update'
    permission_denied_message = 'Acceso denegado. No posees permiso para actualizar usuarios. Contacta a tu administrador'
    raise_exception = True
    model = User
    form_class = UpdateUserForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('users:users_list')

    def get_initial(self):
        initial = super(UsersUpdate, self).get_initial()
        try:
            current_groups = self.object.groups.all()
        except:
            # exception can occur if the edited user has no groups
            # or has more than one group
            pass
        else:
            initial['group'] = current_groups
        return initial

    def form_valid(self, form):
        self.object.groups.clear()
        self.object.groups.add(*form.cleaned_data['group'])
        return super(UsersUpdate, self).form_valid(form)

def logued_user(request):
    if get_maintenance_mode():
        return redirect(reverse_lazy('configuration:configuration'))                
    else:
        return redirect(reverse_lazy('patient:patient_index'))

templates/users/delete.html
{% load bootstrap4 %}
{% block content %}

<form role="form" action="{% url 'users:users_delete' object.pk %}" method="post">
    {% csrf_token %}
    <p>Desea eliminar al usuario {{object.username}}?</p>
    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-default" onclick="return cerrar_modal()">Cancelar</a>
</form>

{% endblock %}

{% block finish %}
<script>
    function cerrar_modal(){
        modal.dialog("close");
    }
</script>
{% endblock %}

templates/users/list.html
{% extends 'base/list.html' %}
{% load bootstrap4 %}
{% load configuration_tags %}
{% load staticfiles %}

{% block card-top %}
    <div class="card-header">
        Usuarios
    </div>
    <img class="card-img-top" src="{% static 'img/users.jpg' %}" alt="Card image cap">
{% endblock %}  

    {% block fieldsHeadPrincipalTable %}
        <th>Nombre de usuario</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Activo</th>
        <th>Perfil</th>
    {% endblock %}

      
    {% block fieldsBodyPrincipalTable %}
        {% for user in object_list %}
            <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{% if user.is_active %} Si {% else %} No {% endif %}</td>
            <td><a href="{% url 'users:users_show' user.id %}" class="btn btn-primary btn-sm">Perfil</a></td>
            </tr>
        {% endfor %}
    {% endblock %}


{% block finish %}
    <script>
        $(document).ready(function() 
        {   
            var table = $('#mytable').DataTable( {
                "responsive": true,
                "language": {
                    url: "/static/localizacion/es_ES.json"
                },
                "aoColumnDefs": [{ 
                    "bSortable": false,
                    "aTargets": [4]
                }],
                "lengthChange": false,
                "pageLength": {% items_per_page %}
            } );
        });
    </script>    
{% endblock %}

templates/users/login.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles%}
{% block sideMenu %}    
{% endblock %}
{% block stylesheet %}    
    <link href="{% static 'css/noSidebar.css' %}" rel="stylesheet">
{% endblock %}

{% block topMenu %} <!-- Para que no aparezca la opción "Cerrar sesión" -->
{% endblock %}

{% block content %}
    <div class="container col-lg-3">
        <div class="card mb-3">
            <div class="card-header">Iniciar Sesión</div>
            <img class="card-img-top" src="{% static 'img/medico.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <form  role="form" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-12">
                            {% bootstrap_field form.username %}
                        </div>
                        <div class="form-group col-md-12">
                            {% bootstrap_field form.password %}
                        </div>
                    </div>
                        <center>
                            {% bootstrap_button "Iniciar Sesión" button_type="submit" button_class="btn-primary btn-lg btn-block" %}
                            {% url 'users:users_password_reset' as recover_password_url %}
                            {% bootstrap_button "Olvidé mi contraseña" button_type="link" button_class="btn-link" href=recover_password_url %}
                        </center>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles%}
{% block sideMenu %}    
{% endblock %}
{% block stylesheet %}    
    <link href="{% static 'css/noSidebar.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            <div class="card-body text-center">
                <h4>Su contraseña se reestablecio correctamente</h4>
                {% url 'users:users_login' as login_url %}
                {% bootstrap_button "Iniciar sesion" button_type="link" button_class="btn-primary" href=login_url %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles%}
{% block sideMenu %}    
{% endblock %}
{% block stylesheet %}    
    <link href="{% static 'css/noSidebar.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            {% if validlink %}
            <div class="card-header">
                Nueva Contraseña
            </div>
            <div class="card-body">
                <form  role="form" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.new_password1 label='Nueva Contraseña' %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.new_password2 label='Confirme Contraseña' %}
                        </div>
                    </div>
                    {% bootstrap_button "Cambiar Contraseña" button_type="submit" button_class="btn-primary" %}
                </form>
            </div>
            {% else %}
            <div class="card-body">
                <h4 class="text-center">Enlace invalido. Este enlace ya ha sido utilizado.</h4>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles%}
{% block sideMenu %}    
{% endblock %}
{% block stylesheet %}    
    <link href="{% static 'css/noSidebar.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            <div class="card-body">
                <h4 class="text-center">Te hemos enviado un correo electronico para reestablecer tu contraseña</h4>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/users/password_reset_email.html
Has solicitado reestablecer tu contraseña.
Clickea en el siguiente link para crear una nueva contraseña:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:users_password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

templates/users/password_reset_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles%}
{% block sideMenu %}    
{% endblock %}
{% block stylesheet %}    
    <link href="{% static 'css/noSidebar.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            <div class="card-header">
                Recuperar Contraseña
            </div>
            <div class="card-body">
                <form  role="form" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.email %}
                        </div>
                    </div>
                    {% bootstrap_button "Enviar" button_type="submit" button_class="btn-primary" %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

    <div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Nuevo usuario
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            {% for field in form %}
                                <div class="form-group col-md-6">
                                    {% bootstrap_field field %}
                                </div>
                            {% endfor %}
                        </div>
                        {% bootstrap_button "Registrar" button_type="submit" button_class="btn-primary" %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/show.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load configuration_tags %}
{% load staticfiles %}

{% block content %}
    
    <div class="container col-lg-9">
        <div class="card mb-3 table-responsive">
            <div class="card-block">
                <div class="card-header">
                    Detalles de {{ object.username }}
                </div>
                <div class="card-body">
                    <table class="table table-hover text-center">
                        <tbody>
                            <tr>
                                <td>Nombre de usuario:</td>
                                <td>{{ object.username }}</td>
                            </tr>
                            <tr>
                                <td>Nombre:</td>
                                <td>{{ object.first_name }}</td>
                            </tr>
                            <tr>
                                <td>Apellido:</td>
                                <td>{{ object.last_name }}</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>{{ object.email }}</td>
                            </tr>
                            <tr>
                                <td>Tipos:</td>
                                <td>
                                    {% for group in object.groups.all %}
                                        | {{ group }} |
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr>
                                <td>Activo:</td>
                                <td>{% if user.is_active %} Si {% else %} No {% endif %}</td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-transparent">
                    {% url 'users:users_update' user.id as users_update_url %}
                    <td>{% bootstrap_button "Editar" button_type="link" button_class="btn btn-secondary btn-sm" href=users_update_url %}</td>
                    <a onclick="return abrir_modal('{% url 'users:users_delete' user.id %}','Eliminar usuario')" class="btn btn-danger btn-sm">
                            Eliminar
                    </a>
                    <a href="{% url 'users:users_list' %}" class="btn btn-secondary btn-sm">Volver al listado</a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- MODAL ELIMINAR -->

    <form method="post" class="modal fade" id="modalRemove">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminar usuario</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger">
                        ¿Está seguro de eliminar al usuario {{ object.username }}?
                    </div>
                </div>
                <div class="modal-footer ">
                    <input type="hidden" id="deleteId" name="deleteId">
                    <button type="submit" class="btn btn-danger" ><span class="glyphicon glyphicon-ok-sign"></span>Si</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>No</button>
                </div>
            </div>
        </div>
    </form>
    
    <!-- FIN MODAL ELIMINAR -->

{% endblock %}

{% block finish %}
<div id="popup"></div>

<script>
    var modal;
    function abrir_modal(url, titulo){
        modal = $('#popup').dialog(
        {
            title: titulo,
            modal: true,
            width: 500,
            resizable: false
        }).dialog('open').load(url)
    }

</script>
{% endblock %}

templates/users/update.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container col-lg-9">
    <div class="card mb-3 table-responsive">
        <div class="card-block">
            <div class="card-header">
                Modificar usuario
            </div>
            <div class="card-body">
                <form  role="form" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.username %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.first_name %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.last_name %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.email %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.group %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.is_active %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.password1 %}
                        </div>
                        <div class="form-group col-md-6">
                            {% bootstrap_field form.password2 %}
                        </div>
                    </div>
                    {% bootstrap_button "Aceptar" button_type="submit" button_class="btn-primary" %}
                </form>
            </div>
            <div class="card-footer bg-transparent">
                <a href="{% url 'users:users_show' user.id %}" class="btn btn-secondary btn-sm">Volver al perfil</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}